### ISSUE TITLE
online documenation seems to deliver an old bundle

### ISSUE THREAD

**Issue by thet** [Patternslib/Patterns#509] opened 2017-06-27 10:44 UTC
for the gallery, there are three examples: http://patternslib.com/gallery/

the first one is working, last two not. I assume, the bundle is not up to date?

**Comment by pilz** [comment] 2017-08-28 15:03
@thet I have updated the site and the bundle is Patternslib 2.1.2-dev. 
I see all three examples open in a lightbox. Is that working as intended? 

If not, we have a different issue.

**Comment by pilz** [comment] 2018-06-18 12:55
That should be fixed

**Closed by pilz** 2018-06-18 12:55 UTC
