### ISSUE TITLE
a.pat-modal inside form.pat-inject

### ISSUE THREAD

**Issue by reinhardt** [Patternslib/Patterns#393] opened 2015-02-04 10:42 UTC
When I put an a.pat-modal inside a form.pat-inject, the modal behaves unexpectedly. If it is supposed to load from the current page, it shows the form target instead of the specified source. If it is supposed to load via ajax, it doesn't load at all but causes javascript warnings.

Example markup:

```
                <div id="contacts">
                    <form action="modaltest.html#contacts"
                        method="get"
                        class="pat-inject"
                        data-pat-inject="#contacts"
                        id="filters">
[...]
                        <button type="submit">Submit</button>

                        <p>
                            <a href="#warning"
                                class="pat-modal"
                                id="mailto-contacts-modal-in"
                                title="Link inside form">Link inside form</a>
                        </p>
                    </form>
                    <a href="#warning"
                        class="pat-modal"
                        id="mailto-contacts-modal-out"
                        title="Same link outside form">Same link outside form</a>
                </div>
```
#mailto-contacts-modal-in shows the contents of #contacts inside the modal (see screenshot). #mailto-contacts-modal-out works fine.

![modal test](https://cloud.githubusercontent.com/assets/202439/6038929/7b861778-ac59-11e4-82f2-0fa741cdffe4.png)

If I use something like 'href="warning.html#content"' instead, i.e. load via ajax, then the first link causes the following warnings:

```
 patterns.pat.inject: No source elements for selector: #contacts [div, constructor: function, init: function, selector: "", jquery: "1.8.3", size: function…]
 patterns.pat.inject: Aborting injection, source not found: [prevObject: jQuery.fn.jQuery.init[0], context: undefined, constructor: function, init: function, selector: ""…]
```

**Comment by pilz** [comment] 2017-08-31 14:54
@reinhardt is this still a problem? if not, can I close it?

**Comment by reinhardt** [comment] 2017-08-31 15:27
Is there any reason to believe it has been fixed in the meantime? I can double check if you want.

**Comment by pilz** [comment] 2017-08-31 15:48
It could be with the new modals. Maybe not, but as this is very old, there is a chance that nobody needs this after all. And then I would close it.

**Comment by reinhardt** [comment] 2018-02-16 07:41
We don't "need" it in the sense that we have a workaround where we would use it. So there is no urgency, but imho it would be good to be able to combine modals and form injection and it may save us some future debugging.

**Comment by reinhardt** [comment] 2018-02-16 07:46
For reference: this is the real world example with the workaround (pat-forward)

https://github.com/syslabcom/Staralliance/blob/master/src/staralliance/contacts/browser/templates/app.pt#L111

**Comment by reinhardt** [comment] 2018-02-16 08:24
I just double checked - the problem is not fixed; without the pat-forward the modal doesn't load. Even worse, the workaround also seems to be broken. I suppose there is some urgency after all.

**Comment by reinhardt** [comment] 2018-02-16 08:33
Sorry, false alarm. The workaround is working. Don't panic.

**Comment by ale-rt** [comment] 2019-03-15 15:08
Note minimal markup to reproduce this is:
```
<form data-pat-inject="source: #modal-source-headerlesss; target: #modal-source">
  <a href="#modal-source" class="debugme pat-modal">Modal</a>
</form>
```
You do not even need an element with pat-inject class, what actually triggers the error is the `data-pat-inject`.
The reason is the overloading of the inherit parameter in the parser function described in detail here:
- https://github.com/Patternslib/Patterns/issues/627

**Closed** 2019-03-15 16:02 UTC
Labels: Pattern injection, Pattern modal, in progress
