### ISSUE TITLE
Smooth scroll pattern

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#385] opened 2014-11-28 10:15 UTC
For pat-smooth-scroll we should select an existing smooth scroll pattern and port it to a Pattern. 

It would be triggered by `class="pat-smooth-scroll` on any anchor tag that contains a url fragment. For instance: 

    <a href="#my-id" class="pat-smooth-scroll">
        Smooth scroll to My ID!
    </a>

or in combination with injection:  

    <a href="#my-id" class="pat-smooth-scroll pat inject">
        Inject something and smooth scroll to the target ID!
    </a>`

I could imagine a property `speed` to indicate the desired velocity, with a default set to 0.2s.

There are also situations where injection is desired in combination with form submits that use injection. In that case the `pat-smooth-scroll` could be applied on the form tag:

    <form action="my-file.html#my-id" class="pat-smooth-scroll pat-inject">
        …

**Comment by jcbrand** [comment] 2015-04-30 12:05
This is a duplicate of #314, which one can we close?

**Closed by jcbrand** 2015-04-30 12:05 UTC
