### ISSUE TITLE
store registered patterns on a global object

### ISSUE THREAD

**Issue by vangheem** [Patternslib/Patterns#396] opened 2015-02-10 05:52 UTC
We are hitting a scenario where there are multiple built javascript bundles being used in a CMS(plone).

With multiple bundles, all using the registry, perhaps different patterns, it's possible that the registry is included a couple of times on the page. This causes some things not being registered when the scan occurs.

I would like to move the registered patterns into a global variable so it can work in these cases. Thoughts?

@jcbrand

**Comment by jcbrand** [comment] 2015-02-10 09:43
Under what circumstances would it be reasonable or acceptable to have multiple bundles?

If you have multiple Patterns' bundles, then each will have its own local registry and ``registry.init`` will be called in each of them.

It sounds more to me like you'll have patterns being registered and invoked multiple times (once for each registry in each of the bundles) than that you'll have patterns not being registered at all.

Can you provide an example or explanation why some patterns might not be registered or scanned due to multiple local registries?

Patterns might not be invoked during a scan if they weren't registered in the registry.

In Patternslib this must be done explicitly:
https://github.com/Patternslib/Patterns/blob/master/src/pat/bumper.js#L163

In Mockup it's done implicitly:
https://github.com/plone/mockup-core/blob/master/js/pattern.js#L97

Whether a mockup pattern is registered in a specific registry will mostly depend whether it's included in the same bundle as that registry.

I'd prefer to really know what's going on before we seriously consider making the registry global, which I don't consider good practice.

I'll make a test with two Patternslib-only bundles to see what happens. I see in the mockup Makefile that it generates multiple bundles (bundle-widgets, bundle-structure, bundle-plone etc.).

Can you please explain to me what their roles are and with which ones I can test?

**Comment by jcbrand** [comment] 2015-02-10 13:15
I did a quick test. I included two Patternslib bundles and then tested the pat-switch pattern.

It behaved like I expected, the pat-switch pattern gets scanned and invoked by both bundles.

This of course might indeed be an issue when patterns are written in such a way that they may never be called redundantly, but it's not the same behavior as you mentioned.

Granted, this is a very simple test and there might be something else going on.

**Comment by vangheem** [comment] 2015-02-10 14:39
So here the the scenario that we're running into.

Bundle 1: includes a bunch of patterns, including Pattern X. To load the patterns it does something like: require(['jquery', 'pat-registry', 'pattern-x'], function($, registry){ $(document).ready(function(){ registry.scan($('body')); }) });

Bundle 2: includes some more patterns, including Pattern Y. Here is where it gets dicey. Pattern Y depends on Pattern X because it's a bit more complicated and composed of others. Additionally, it needs to run similar scan code to Bundle 1 so Pattern Y gets loaded. However, that'll also scan pattern X a second time.

For us, a bundle is a package of resources. Things might get included twice, yes, but it's an isolation thing and a small penalty you pay for having the modularity. The simple case I'm working on right now is splitting the 1 bundle we have right now into 2 separate bundles, one for all plone and one only for logged in users.
 
You might ask why I'm scanning in both bundles also. Well, in development mode(non-compiled), it's indeterminate which require call will finish first so you can't simple order them in a way where the scan is always called at the correct time.

so really, in addition to patterns being registered with a global objects, I'd also like to set an attribute on  scanned patterns to see if they've already been initialized and to not do it again if they were.

**Comment by wichert** [comment] 2015-02-10 14:42
Essentially you are loading two conflicting bundles (they overlap) and expect things to magically work. I don't see that being a reasonable assumption, or why Patterns needs to support it.

If you want to do this kind of thing I would suggest to create a bundle with just Patterns core, and separate bundles with one or more patterns. You can then load things at will without risking overlap.

**Comment by vangheem** [comment] 2015-02-10 14:46
"expect things to magically work" well okay. I've presented the problem and I know a simple solution. It's not "magic."

I think it's reasonable what I'm requesting.

**Comment by vangheem** [comment] 2015-02-10 14:48
I think what I could do is just do more targeted scans instead of scanning the body tag. I know the patterns I'm targeting in each scenario so I could just aggregate the trigger property and only scan those elements.

**Comment by jcbrand** [comment] 2015-02-10 14:56
> You might ask why I'm scanning in both bundles also. Well, in development mode(non-compiled), it's indeterminate which require call will finish first so you can't simple order them in a way where the scan is always called at the correct time.

I'm not sure I understand what you mean here, require call to what?

Patterns are scanned only after the DOM is ready and only after all patterns have been loaded with require.js. The scan order is leaves first. So it's predictable.

> I think what I could do is just do more targeted scans instead of scanning the body tag. I know the patterns I'm targeting in each scenario so I could just aggregate the trigger property and only scan those elements.

Sounds like this might be related to the above quoted sentence, right? There are multiple patterns all triggered merely on ``body`` and you then don't know the order in which they will be invoked. Correct?

**Comment by vangheem** [comment] 2015-02-10 15:00
> I'm not sure I understand what you mean here, require call to load what?
To load the scan code--on document load. Since in development mode, it's slow, it's possible the document is already loaded before all the js is loaded. We're using requirejs and it's all dependency management and callbacks

**Comment by vangheem** [comment] 2015-02-10 15:02
Mockup project could also just fork the pat-registry. We would still adhere to the conventions used in patternslib so they'd both be compatible.

**Comment by jcbrand** [comment] 2015-02-10 15:08
> Since in development mode, it's slow, it's possible the document is already loaded before all the js is loaded.

Are you saying the scanner executes before patterns are loaded?

``registry.init`` is called only after all the patterns are loaded with require.js. See here:
https://github.com/Patternslib/Patterns/blob/dd16fd2ccc82dd5e7875987a64382b96d773ad9d/src/patterns.js#L64

And in ``registry.init`` it listens to ``$(document).ready`` before starting to scan.

**Comment by vangheem** [comment] 2015-02-10 15:13
> Are you saying the scanner executes before patterns are loaded?

No, I'm saying that by the time the first require() is finished loading it's dependencies, the document has already been loaded. And then, it's impossible to know if bundle 1 or bundle 2 will load their pattern requirements first.

So it's:

- js, requirejs loaded, dependencies specific, requirejs starts loading all dependencies
- document finishes loading
- requirejs finishes loading dependencies for bundle 1 and document is already loaded, scan takes place
- bundle 2's dependencies finish loading, do we scan again? Some patterns are re-registered(which I'm frankly okay with because I'd like people to be able to override patterns) so we'll scan some elements twice if we scan again. If we do not scan here, these patterns never got scanned for.

This whole problem really has to do with quirks between compiled and non-compiled mode. If we always just compiled into one huge bundle, this wouldn't be a problem; however, that's not how it's going to work for us.

**Comment by wichert** [comment] 2015-02-10 15:17
@vangheem as I see it Patterns is essentially a small app running in your document, and you are trying to run two instances of that at the same time. I'm not surprised at all that does not work.

What I don't understand is why you want to do that. Why can't your bundle 2 not consist of just the extra patterns you want to load?

You also mentioned wanting to override patterns that are already in a bundle. That really is not a Patterns-problem, or something Patterns can support: that will require support from RequireJS, or (much better) not using bundles or creating a custom bundle.

**Comment by vangheem** [comment] 2015-02-10 15:20
I'm not surprised it doesn't work either. That's why I'm trying to fix it.

Bundle 2 depends on some more basic bundles from Bundle 1. 

For example, our structure pattern has modals in it. The structure pattern is only necessary for logged in users.

Again, it's not just about registration though. It's also about scan timing in non-compiled form.

**Comment by vangheem** [comment] 2015-02-10 15:22
Something like this would be the proposed change::

```
         log.info('I will not catch init exceptions');
     }
 
+    if(window.registered_patterns === undefined){
+        window.registered_patterns = {};
+    }
+
     var registry = {
-        patterns: {},
+        patterns: window.registered_patterns,
         // as long as the registry is not initialized, pattern
         // registration just registers a pattern. Once init is called,
         // the DOM is scanned. After that registering a new pattern
@@ -57,6 +61,7 @@ define([
         },
 
         scan: function registry_scan(content, patterns, trigger) {
+
             var $content = $(content),
                 all = [], allsel,
                 $match, plog;
@@ -96,7 +101,8 @@ define([
                     pattern = registry.patterns[name];
                     if (pattern.init) {
                         plog = logger.getLogger("pat." + name);
-                        if ($el.is(pattern.trigger)) {
+                        if ($el.is(pattern.trigger) && !$el.is('.patternslib-initialized')) {
+
                             plog.debug("Initialising:", $el);
                             try {
                                 pattern.init($el, null, trigger);
@@ -105,6 +111,7 @@ define([
                                 if (dont_catch) { throw(e); }
                                 plog.error("Caught error:", e);
                             }
+                            $el.addClass('patternslib-initialized');
                         }
                     }
                 }
```

**Comment by wichert** [comment] 2015-02-10 15:22
As I see it the problem here is trying to use (conflicting) bundles during development. If it was up to me I would be very tempted to say "don't do that" and leave it at that. Bundles and development just don't mix well.

**Comment by wichert** [comment] 2015-02-10 15:23
Your fix still doesn't work: it creates interesting races when two scans are happening at the same time.

**Comment by vangheem** [comment] 2015-02-10 15:25
doesn't javascript run in a single thread?

**Comment by wichert** [comment] 2015-02-10 15:30
Yes, but are there hard guarantees on events never interrupting running code? For example a finished download from RequireJS triggering extra logic in the middle of your code?

**Comment by vangheem** [comment] 2015-02-10 15:32
Yes, I think that would be possible in non-compiled mode.

**Comment by vangheem** [comment] 2015-02-10 15:35
Anyways, it sounds like patternslib is not interested in a change like this.

I'm trying to identify common pitfalls and solutions to them for working with requirejs, patterns and Plone. 

This is a glaring one and I think the only solution is to do more targeted scans.

Or we just fork the registry.

**Comment by jcbrand** [comment] 2015-02-10 15:42
@vangheem What about @wichert's solution that the registry is included in one bundle and the other bundle just includes extra patterns?

**Comment by vangheem** [comment] 2015-02-10 15:45
We'd need to do some magic where requirejs would skip including the pat-registry file.

Would also still have scanning problem in non-compiled mode.

**Comment by jcbrand** [comment] 2015-02-10 17:26
I've looked at the code in more details and played around with it on Plone 5 and I think I have a much clearer idea now of what you mean when you say "bundles".

You refer to these:
https://github.com/plone/mockup/tree/master/mockup/js/bundles

In Patterns we name the compiled file a bundle, so I was thinking that you were always referring to multiple compiled bundles. Which made what you said quite confusing to me.

Looking at those bundles, they are similar to the  [patterns.js](https://github.com/Patternslib/Patterns/blob/dd16fd2ccc82dd5e7875987a64382b96d773ad9d/src/patterns.js#L64) file I linked to.

Already I can see a bug there. The bundles should call ``registry.init`` and not ``registry.scan``, or at least set ``registry.initialized = true;`` after scanning.

The reason for this is so that the registry will always rescan new patterns when they are registered **after** the initial scan. See [here](https://github.com/Patternslib/Patterns/blob/dd16fd2ccc82dd5e7875987a64382b96d773ad9d/src/core/registry.js#L142).

So, let's look at some of your statements in light of the above:

> * js, requirejs loaded, dependencies specific, requirejs starts loading all dependencies
document finishes loading
> * requirejs finishes loading dependencies for bundle 1 and document is already loaded, scan takes place
> * bundle 2's dependencies finish loading, do we scan again?

No. The registry will automatically scan those patterns as soon as they are registered and they get registered implicitly in Mockup as soon as they are loaded.

But that is if ``registry.initialized = true``, which is why ``registry.init`` must be called.

> Some patterns are re-registered(which I'm frankly okay with because I'd like people to be able to override patterns) so we'll scan some elements twice if we scan again. If we do not scan here, these patterns never got scanned for.

Due to above mentioned bug.

**Comment by vangheem** [comment] 2015-02-10 17:31
That gets us closer.

If a pattern is registered an additional time, it's still going to scan twice.

**Comment by vangheem** [comment] 2015-02-10 17:32
Rather, it's okay if they get scanned an additional time; however, init should not be called on them again.

**Comment by jcbrand** [comment] 2015-02-11 10:44
@vangheem I've made three pull requests which implement the change I mentioned above.

I tested the latest Plone 5 and it looks good to me. Can you please also take a look? If there is still a problem, please let me know how I can go about replicating it.

> If a pattern is registered an additional time, it's still going to scan twice.

No, it won't:
https://github.com/Patternslib/Patterns/blob/dd16fd2ccc82dd5e7875987a64382b96d773ad9d/src/core/registry.js#L122

**Comment by vangheem** [comment] 2015-02-11 14:41
I tested this same strategy and it didn't work for me. Still doesn't hit all scenarios.

Yes, I see that it checks if a pattern is already registered; however, if you have 2 copies of pat-registry included(one for each bundle), since the registry isn't global, it'll still get called twice.

Originally I tested your fix and it wasn't enough. Here is a registry that works all the time.https://github.com/plone/mockup-core/blob/master/js/pattern.js

I also thought this situation is similar to requirejs which also needs to maintain a global registry.

**Comment by jcbrand** [comment] 2015-02-11 15:02
> I tested this same strategy and it didn't work for me. Still doesn't hit all scenarios.

Please provide instructions on how to reproduce.

> Yes, I see that it checks if a pattern is already registered; however, if you have 2 copies of pat-registry included(one for each bundle), since the registry isn't global, it'll still get called twice.

I'm kind of surprised that there would be two distinct registries. Wouldn't require.js reuse the original pat-registry which it already has loaded. Why would it load the file anew?

When I was testing it, it looked to me to be the same registry. For example the resourceregistry.js bundle was loading after the plone.js bundle. In the resourceregistry.js bundle ``registry.initialized`` was ``true``, which means that it's the same registry as the one from plone.js in which the registry was initialized.

> Originally I tested your fix and it wasn't enough. Here is a registry that works all the time.https://github.com/plone/mockup-core/blob/master/js/pattern.js

You linked to the base pattern, not to a registry. Also, a diff would be best.

> I also thought this situation is similar to requirejs which also needs to maintain a global registry.

Quickly looking at the require.js code, I don't see that the registry is global. It's in a closure:
https://github.com/jrburke/requirejs/blob/master/require.js#L212

So it's local to that instance of require.js.

**Comment by vangheem** [comment] 2015-02-11 15:08
You can open a terminal and inspect the "requirejs.s.contexts" for globals.

I'll give your pull requests a try. I think it'll depend on how requirejs works in dev and compiled form when the pat-registry is registered twice.

**Comment by jcbrand** [comment] 2015-02-11 15:22
This is what I get:

``` Javascript
Object.keys(requirejs.s.contexts)
["_"]

Object.keys(requirejs.s.contexts['_'])
["config", "contextName", "registry", "defined", "urlFetched", "defQueue", "Module", "makeModuleMap", "nextTick", "onError", "configure", "makeShimExports", "makeRequire", "enable", "completeLoad", "nameToUrl", "load", "execCb", "onScriptLoad", "onScriptError", "require", "startTime"]
```

That is not global though, it's specific to that instance of require.js and it's different to what you want to do.

If you somehow had two different requirejs instances, then each would have its own registry and it wouldn't be shared between them. Exactly like Patternslib behaves currently.

**Comment by vangheem** [comment] 2015-02-11 15:25
I'm not sure, there is all kinds of checks in requirejs to see if it's already defined:

```
if (isFunction(requirejs)) {
            //Do not overwrite an existing requirejs instance.
            return;
        }
```

**Comment by jcbrand** [comment] 2015-02-11 15:32
That prevents another require.js instance from being created, probably to avoid a similar situation where you have two instances each with its own registry.

They implemented a different solution however (allowing only one instance), rather than allowing multiple require.js instances which all access a global registry, which would be the equivalent of what you proposed.

**Comment by vangheem** [comment] 2015-02-11 15:37
As far as I can tell, your fixes should work.

requirejs will not allow you to redefine an existing module so even though it's being included twice, when compiled, it'll only use the one that is defined first.

I'll work on merging your patches.

**Comment by jcbrand** [comment] 2015-02-11 15:43
That would be great thanks.

**Closed** 2015-02-11 15:50 UTC
