### ISSUE TITLE
New pattern pat-tooltip-ng

### ISSUE THREAD

**Issue by pilz** [Patternslib/Patterns#661] opened 2019-06-24 20:01 UTC
Create a new pattern in patternslib/src/pat/tooltip-ng
* It should not be included by default in the src/patterns.js file.
* It should be made available in the webpack/base.conf.js under the resolve alias "pat-tooltip-ng"
* It should still listen for the original trigger class "pat-tooltip"

So if someone wants to switch to the new tooltip pattern, he only needs to change his patterns.js file to reference pat-tooltip-ng instead.

The new tooltip pattern should use tippy.js and popper.js as prototyped in the new-tooltip-lib branch. This branch is only a test and should only be used as inspiration.

The original signature of the pat-tooltip pattern should stay intact. If it has to change, we need to closely document that and communicate it to Cornelis to determine the impact.

Configure the library to reflect what we have already in pat-tooltip (I am thinking of white tooltips and a triangle as pointer) but don't start designing css.

If you can find a set of sane defaults for the tippy configuration, do it at your own discretion. (Like turning of stupid animations)

This will make #586 obsolete.

**Comment by pilz** [comment] 2019-06-24 20:02
It would be great to have this by the 22.7. when Cornelis returns from holiday.

**Comment by fulv** [comment] 2019-08-12 21:09
Please see branch pat-tooltip-ng.  This implements a new pattern `pat-tooltip-ng`.

If you run `npm start` and load the page http://localhost:3001/src/pat/tooltip-ng/index.html, I have created examples of all the `data-pat-tooltip-ng` arguments that are currently implemented, which are:

- `source`
- `trigger`
- `content`
- `class`

The remaining arguments should be pretty quick to implement now that I have solid tests.

A few notes:
- the default tippy style is to have tooltip content centered, instead of left-aligned (noticeable with the ajax examples that inject longer content)
- Initially, I built this to replace and load **instead of** `pat-tooltip`, but then I realized I need to have them running both at the same time in order to test and compare functionality side by side.  Making this new tippy-based tooltip replace the old `pat-tooltip` will be pretty easy and can be left as the last step.

**Comment by fulv** [comment] 2019-08-14 03:46
I have implemented `delay` and added it to the list above.  Pull the `pat-tooltip-ng` branch.

**Comment by cornae** [comment] 2019-08-14 09:07
I ran the demo locally. I noticed that the common styles were not loaded on this demo. After I restored the link to the common styles, the bubbles were displaced. 

<img width="467" alt="image" src="https://user-images.githubusercontent.com/738601/63008817-9a495080-be83-11e9-92af-5f04f7b3a282.png">

Can you have a look?

**Comment by cornae** [comment] 2019-08-14 09:16
If you narrow the browser window until div.container (the centred element) matches the viewport size, then the positioning is fine. But once the viewport is wider and the design centres itself, the offset is calculated wrongly.

**Comment by fulv** [comment] 2019-08-15 01:22
I see what you are saying, but I have not been able to isolate the problem.

I tried to reproduce the issue with pure tippy.js (no patterns), and so far have failed to do so:

https://codepen.io/fulv/pen/jONqVbL

Can you give it a try in codepen?
If we can't, then it might actually not be a tippy problem, but ours.

**Comment by cornae** [comment] 2019-08-15 08:24
I can neither reproduce it in codepen nor in the also centred design of https://atomiks.github.io/tippyjs/

Is there anything you need me to do to help finding the cause?

**Comment by fulv** [comment] 2019-08-16 00:59
@cornae I take it that your theory is that the problem occurs when it's the `<body>` element that has auto margins?  That would explain why it can't be reproduced in codepen, since it doesn't really let you set a `<body>`.
So I created a test page here:  http://tippy.soliton.consulting/, and it still doesn't reproduce the issue.
I'm starting to think that maybe there is something else in our CSS that is giving trouble.

On the other hand, maybe your commit is sufficient for now as a workaround, and it's not worth chasing this down further.

**Comment by fulv** [comment] 2019-08-16 03:49
Look at http://tippy.soliton.consulting/commonstyle.html.  This one has the problem and the only difference is the common.css inclusion.

**Comment by fulv** [comment] 2019-08-16 03:52
Also, if I comment out the `body { position: relative; }` rule from common.css, it works again.

**Comment by cornae** [comment] 2019-08-16 13:53
Fulvio, the problem is not necessarily auto margins, but rather the combination of position relative and any margin. In other words: treating the body as a container element. Since my commit too common.css this is fixed.

https://github.com/Patternslib/Patterns/commit/e9dbdb0e807379ebc9e2f0391d6329415696a979

This doesn't occur in any of our current projects, so for me it's fine now concerning this issue.

**Comment by fulv** [comment] 2019-08-17 03:00
Update: mark-inactive is implemented.

**Comment by pilz** [comment] 2019-08-20 16:31
tooltip-ng.js is currently using the tippy light theme css file. We could try removing that setting and let the designer provide its own css. That is probably the magic styling that Cornelis wrote about.

I propose the following next steps:
1. Remove theme
2. Merge the pattern as it currently is under the name of pat-tooltip-ng but change the trigge
3. Then I can include it into the ploneintranet prototype and load it along side the old pat-tooltip, but Cornelis can start working on styling based on example by manually changing pat-tooltip classes to pat-tooltip-ng experimentally.

Any objections @fulv?

**Comment by fulv** [comment] 2019-08-22 02:31
@Alexander Pilz <pilz@syslab.com> no objections, I've just been a bit ill
these last few days.  I'll get back to you tomorrow.
-- 
Fulvio

**Comment by fulv** [comment] 2019-08-29 22:30
Update:  `position-list` is partially implemented.  It only looks at the first value and ignores all the following ones.

> The jasmine tests for `tl`, `tm`, `tr`, `rt`, `rm`, and `rb` are failing, although on the demo page those options work fine.  I tried adding lots of padding and margin to `<body>` and `div#lab`, as well as increasing the size of the HeadlessChrome viewport, to no avail.  So I've disabled them for now.

**Comment by fulv** [comment] 2019-09-05 23:57
Update: Both `position-list` and `position-policy` are implemented now.  They are demonstrated with examples in the index.html file which you can run as usual with `make designerhappy` or `npm start`.  

`position-policy` is a little odd:  it seems to only allow for a single "fall-back" position.  IOW, of all those listed in `position-policy`, tippy seems to pick just one that will work better and ignore all the others.

**Comment by pilz** [comment] 2019-10-07 13:37
I am now trying to merge this and integrate it into the prototype for Cornelis to style.
For that I have created the branch pat-tooltip-ng-rebased which rebases on master and continue there.

**Comment by pilz** [comment] 2019-10-07 13:38
See https://github.com/Patternslib/Patterns/pull/681

**Comment by pilz** [comment] 2019-10-07 13:44
@fulv I merged the rebased branch. Please do any work that you might need to do on a new branch.
I am now handing this via proto to Cornelis.

**Comment by fulv** [comment] 2019-10-07 15:46
I have the `closing` almost done.  I'll do it on a new branch.  It will also need CSS.

**Comment by fulv** [comment] 2019-10-07 15:48
By the way, `height` is going to be tough because tippy lets you control the width, but not the height.  I have no insight into how important `height` would be to implement.

**Comment by pilz** [comment] 2019-10-15 09:11
Great! Let's ask @cornae about the importance of height. Perhaps it is enough if tippy handles it.
Cornelis has started trying it out on the oira prototype and we are fixing as we go along.

**Comment by pilz** [comment] 2019-10-15 09:13
Note to dev/self: So far I have done one change to the pattern. The inject should only inject the contents of the targeted injection element.
See https://github.com/Patternslib/Patterns/commit/d30c2e3094b44741d4b905d0a93a12698466f890

The reason is that the tooltip can be present on the current page but within a hidden element. Injecting that hidden element would render the tooltip content hidden again. Cornelis said that this was already a rule followed in the old tooltip pattern so it seemed straight forward to change again.

**Comment by pilz** [comment] 2019-10-15 12:01
Another note. In an interactive debugging session with Cornelis, I did a quick shot and removed the js-included light theme css file from the pattern. This solves one problem for Cornelis where he got styles in twice (once his own statically included ones and the same loaded by js) which prevented him from properly overriding them.
But as a consequence, the tooltip-ng tests are now broken. I still need to understand why.
Just a warning :)

**Comment by cornae** [comment] 2019-10-15 13:55
Tippy should itself handle the height. Width I like to set through the CSS.

**Comment by pilz** [comment] 2019-10-15 15:54
@fulv I am sorry, I have messed around :)
Turns out tippy <5.0 always forcefully included css. This collides with Cornelis' componentised css approach where he fully controls, and overrides, the css. 
I found in https://github.com/atomiks/tippyjs/blob/master/MIGRATION_GUIDE.md that tippy >=5 makes the css includes optional. So my latest commit to master bumps tippy. I applied the changes where I understood the migration guide and now we have unstyled popovers on the demo page in patterns. I will hand this now to Cornelis to see if this fixes his issues. 
However the tests are still broadly broken. (26 red).

**Comment by pilz** [comment] 2019-10-16 08:30
@fulv I think I need your help understanding the test failures. I would love to try to fix them but currently I am puzzled how to debug the problem that the _onShown event is not called.
Any idea?

**Comment by fulv** [comment] 2019-10-29 12:23
@pilz Update: I've been digging into the _onShown issue, but it's complicated.  Something definitely changed in tippy 5's handling of that lifecycle event.  However, I see that it broke in cb984eb3af10a76b6f7eaa917fbe9b4cb6a2f6e4.  Will continue tomorrow.

**Comment by fulv** [comment] 2019-10-29 12:24
That comment ^^^^^  was written yesterday

**Comment by pilz** [comment] 2019-11-25 09:23
This has been closed accidentally. The tests are still failing but outcommented now.

**Comment by pilz** [comment] 2019-12-03 10:49
related to #859

**Closed** 2020-10-19 09:32 UTC
Labels: New Pattern, Pattern tooltip, in progress
